name: Build NoCheatPlus

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    if: "github.actor != 'dependabot[bot]'"
    steps:
      - uses: actions/checkout@main
      - name: Set up JDK 21
        uses: actions/setup-java@main
        with:
          java-version: 21
          distribution: temurin

      - name: Build NoCheatPlus
        run: mvn clean package -P nonfree_build -P all

      - name: Upload NoCheatPlus
        uses: marvinpinto/action-automatic-releases@master
        with:
          title: "NoCheatPlus"
          automatic_release_tag: "ncp"
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          files: "target/*.jar"
          prerelease: true
